# Generated by Django 5.0.2 on 2024-03-01 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_room', models.CharField(max_length=5)),
                ('type_room', models.CharField(help_text='Economy/Semi-suite/Luxury', max_length=10)),
                ('guest_name', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rental_days', models.IntegerField()),
            ],
        ),
    ]
