# Generated by Django 5.0.2 on 2024-03-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_BOOKING', '0002_guest_remove_bookingroom_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='guest_surname',
            field=models.ForeignKey(default='Secret', on_delete=django.db.models.deletion.CASCADE, to='APP_BOOKING.guest'),
        ),
    ]
