# Generated by Django 5.0.2 on 2024-03-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_BOOKING', '0004_alter_bookingroom_guest_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='guest_surname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP_BOOKING.guest'),
        ),
    ]
